name: fixo_mechanic
description: FIXO.GO mechanic app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase (compatible generation)
  firebase_core: ^2.25.4
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.5

  # Maps
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Location
  geolocator: ^10.1.1

  # Geo queries
  geoflutterfire2: ^2.3.15

  # Networking
  dio: ^5.4.3

  # Material You
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true