name: Build Signed Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > app/android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> app/android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> app/android/key.properties
          echo "storeFile=../upload-keystore.jks" >> app/android/key.properties

      - name: Install dependencies
        run: flutter pub get
        working-directory: app

      - name: Build Signed APK
        run: flutter build apk --release
        working-directory: app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk