name: Build Signed Flutter APK for mechanic

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        working-directory: app/mechanic

      - name: Build Signed APK
        run: flutter build apk --release
        working-directory: app/mechanic
        
      - name: Extract SHA fingerprints
        working-directory: app/mechanic
        run: |
          keytool  -printcert -jarfile build/app/outputs/flutter-apk/app-release.apk
        
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apk
          path: app/mechanic/build/app/outputs/flutter-apk/app-release.apk
          