name: Get Debug SHA-1

on:
  workflow_dispatch:   # Run manually

# ✅ Required permission to push commits
permissions:
  contents: write

jobs:
  sha1:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'


      # 4️⃣ Extract SHA-1 into file
      - name: Get  SHA
        run: |
          keytool -list -v -keystore upload-keystore.jks -alias upload